GET http://localhost:4000/me

###
GET http://localhost:4000/heroes

###
POST http://localhost:4000/heroes
Content-Type: application/json

{
	"id": "69",
	"name": "Batman",
	"powerstats": {
		"intelligence": "81",
		"strength": "40",
		"speed": "29",
		"durability": "55",
		"power": "63",
		"combat": "90"
	},
	"biography": {
		"full-name": "Terry McGinnis",
		"alter-egos": "No alter egos found.",
		"aliases": ["The Tomorrow Knight"],
		"place-of-birth": "Gotham City, 25th Century",
		"first-appearance": "Batman Beyond #1",
		"publisher": "DC Comics",
		"alignment": "good"
	}
}

###
GET http://localhost:4000/heroes/60e4549f61fb2150a0dd62cc

###
GET http://localhost:4000/heroes/bio/60e46496acf4782ae8008a39

###
DELETE http://localhost:4000/heroes/60e4549f61fb2150a0dd62cc

###

PATCH http://localhost:4000/heroes/60e5a660f9c5bb2f10616ac5
Content-Type: application/json

{
	"biography.full-name": "Bruce Wayne"
	
}

// "Content-Type" permet de spécifier le type d'info envoyé par le client. c'est l'équivalent de mettre une extension à notre fichier