GET http://localhost:3000/me

###

GET http://localhost:3000/heroes

###
POST http://localhost:3000/heroes
Content-Type: application/json

{
	"id": "69",
	"name": "Batman",
	"powerstats": {
		"intelligence": "81",
		"strength": "40",
		"speed": "29",
		"durability": "55",
		"power": "63",
		"combat": "90"
	},
	"biography": {
		"full-name": "Terry McGinnis",
		"alter-egos": "No alter egos found.",
		"aliases": ["The Tomorrow Knight"],
		"place-of-birth": "Gotham City, 25th Century",
		"first-appearance": "Batman Beyond #1",
		"publisher": "DC Comics",
		"alignment": "good"
	}
}

###
GET http://localhost:3000/heroes/60e459d68977db0de65b3594

###
GET http://localhost:3000/heroes/bio/60e459d68977db0de65b3594

###
DELETE http://localhost:3000/heroes/60e450d9cd7cd00d4cbd9134

###
PATCH http://localhost:3000/heroes/60e5a6872294fd11cb9c3427
Content-Type: application/json

{
	"name": "Batman Modif 3",
	"biography.full-name": "Bruce Wayne 3"

}

###
POST http://localhost:3000/users
Content-Type: application/json

{
	"email": "11@11.11",
	"password": "aaaaaa",
	"role": "user"

}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/60e5b0614ad1dc14c0653269

###
PATCH http://localhost:3000/users/60e5b0614ad1dc14c0653269
Content-Type: application/json

{
	"job": "Dev Frontend"
}

###
DELETE http://localhost:3000/users/60e5b0614ad1dc14c0653269

###
POST http://localhost:3000/login
Content-Type: application/json

{
	"email": "11@11.11",
	"password": "aaaaaa"
}

###
GET http://localhost:3000/protected
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTZlYTEzYjU2MzRjMGRmNGEzNTBhNiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjI1NzUyODY5fQ.v3Iz-vbv3SCuvqZLa5UWor-yPIpr17cd5A6ukeqtIGQ






